config/routes.rb
Rails.application.routes.draw do
  get 'samples/index'

  resources :tests
  resources :samples
  resources :users
  resources :sessions
  resources :blogs
  resources :messages

  root 'users#new'
  delete '/logout'=> 'sessions#destroy'

end

app/models/login.rb
class Login < ActiveRecord::Base
  has_many :messages, foreign_key: :sender_id


  attr_accessor :password, :password_confirmation

  before_save :encrypted_password

  def self.authenticate(email, password)
    login = find_by_email(email)
    return nil if login.blank?
    if login[:encrypted_password] == login.encrypt(password)
      return login
    end
  end

  def encrypt(password)
    Digest::SHA2.hexdigest("#{password}")
  end

  private

  def encrypted_password
    self.salt = Digest::SHA2.hexdigest("#{password}") if self.new_record?
    self.encrypted_password = encrypt(password)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  has_many :recipients
  has_many :users, :through => :recipients


  def user_tokens=(ids)
    self.user_ids = ids
  end
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
end

app/models/sample.rb
class Sample < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages, foreign_key: :sender_id


  attr_accessor :password, :password_confirmation

  before_save :encrypted_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    return nil if user.blank?
    if user[:encrypted_password] == user.encrypt(password)
      return user
    end
  end

  def encrypt(password)
    Digest::SHA2.hexdigest("#{password}")
  end

  private

  def encrypted_password
    self.salt = Digest::SHA2.hexdigest("#{password}") if self.new_record?
    self.encrypted_password = encrypt(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user


  def sign_in user
    session[:user_id] = user.id
    self.current_user = user
  end

  def current_user=user
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    sender_ids = Message.where(sender_id: current_user.id).pluck(:id)
    @sent_messages = Recipient.where(message_id: sender_ids).order('created_at DESC')

    @recieved_message = Recipient.where(user_id: current_user.id)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
  end
  def new
    @login = Login.new
  end

  def create
    @login = Login.new(login_params)
    message = ''
    if login_params[:name].blank? || login_params[:email].blank? || login_params[:password].blank? || login_params[:password_confirmation].blank?
      message = 'not valid'
    end
    if @login.valid? && message.blank?
      @login.save
      redirect_to logins_path
    else
      render 'new'
    end
  end

  private

  def login_params
    params.require(:login).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
    @recipients = User.all
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.valid?
      @message.save
      redirect_to blogs_path
    else
      render 'new'
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :sender_id, user_tokens: [])
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  def index
    # @samples = Sample.all
  end

  def new
    @sample = Sample.new
  end

  def create
    @sample = Sample.new(sample_params)
    if @sample.save
      redirect_to tests_path
    else
      render 'new'
    end
  end

  def destroy
   @sample = Sample.find(params[:id])
     @sample.destroy
   redirect_to tests_path
  end

  private

  def sample_params
    params.require(:sample).permit(:sample_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.present?
      sign_in user
      flash[:notice] = "You have successfully logged out."
      redirect_to blogs_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @tests = Test.all
    @samples = Sample.all
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)
    # if @test.vali?
    p 'eeeeeeeeeeeeeeeeeeeeeeeeee'
    p @test
      if @test.save
      redirect_to tests_path
    else
      render 'new'
    end
  end

  private

  def test_params
    params.require(:test).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    message = ''
    if user_params[:name].blank? || user_params[:email].blank? || user_params[:password].blank? || user_params[:password_confirmation].blank?
      message = 'not valid'
    end
    if @user.valid? && message.blank?
      @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
welcome <%= current_user.name %><br>
<%= link_to 'compose message', new_message_path %><br><br>

<%= link_to 'logout', logout_path  , method: :delete %>
<hr>
Sent Messages
<table>
  <tr>
    <th>Name</th>
    <th>Message</th>
  </tr>
  <% if @sent_messages.present? %>
      <% @sent_messages.each do |message| %>
          <tr>
            <td><%= message.user.name %></td>
            <td><%= message.message.body %></td>
          </tr>
      <% end %>
  <% end %>
</table>
<br>
<hr>

Received Messages

<table>
  <tr>
    <th>Name</th>
    <th>Message</th>
  </tr>
  <% if @recieved_message.present? %>
      <% @recieved_message.each do |message| %>
          <tr>
            <td><%= message.message.sender.name %></td>
            <td><%= message.message.body %></td>
          </tr>
      <% end %>
  <% end %>
</table>
<br>

app/views/logins/index.html.erb
welcome <br>

<%= link_to 'sign', new_session_path %><br><br>

<%= link_to 'Back', root_path %>

app/views/logins/new.html.erb
<%= form_for @login do |f| %>
    name:<%= f.text_field :name, :id => 'abc' %><br>
    email:<%= f.text_field :email %><br>
    Password:<%= f.text_field :password %><br>
    Confirm Password:<%= f.text_field :password_confirmation %><br>
    <%= f.submit 'sign-up', :id => 'xyz' %>
<% end %>

<%= link_to 'signin', new_session_path %>

app/views/messages/new.html.erb
<%= form_for :message, url: messages_path do |f| %>
    <%= f.text_area :body, placeholder: 'messages' %><br><br>
    <hr>
    <% @recipients.each do |user| %>
        <%= user.name %>
        <%= check_box_tag "message[user_tokens][]", user.id, (@message.users.include?(user.id)), id: "user_#{user.id}" %><br>
    <% end %>
    <br><br>
    <hr>
    <%= f.submit 'send message' %>
<% end %>

app/views/samples/index.html.erb
<%= link_to 'create sample', new_sample_path %>

app/views/samples/new.html.erb
<%= form_for @sample do |f| %>
    <%= f.text_field :sample_name %>
    <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
    name:<%= f.text_field :name, :id => 'abc' %><br>
    email:<%= f.text_field :email %><br>
    Password:<%= f.text_field :password %><br>
    Confirm Password:<%= f.text_field :password_confirmation %><br>
    <%= f.submit 'sign-up', :id => 'xyz' %>
<% end %>

<%= link_to 'signin', new_session_path %>